spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      auto-commit: false
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true  # Needed if you use lazy loading outside transactions
        multiTenancy: SCHEMA
        multi_tenant_connection_provider: com.erp.Multitenancy.MultiTenantConnectionProviderImpl
        tenant_identifier_resolver: com.erp.Multitenancy.CurrentTenantIdentifierResolverImpl
        connection.provider_disables_autocommit: true
        connection.isolation: 2  # TRANSACTION_READ_COMMITTED

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/global
    schemas: public
    baseline-on-migrate: true
    table: flyway_schema_history

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_MAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

root:
  email: ${ROOT_EMAIL}
  password: ${ROOT_PASSWORD}
  name: ${ROOT_NAME}

app:
  base-url: /api/v1
  security:
    secret: ${SECURITY_SECRET}
    token-validity:
      access-validity: 3600
      refresh-validity: 1296000
  domain:
    name: ${DOMAIN_NAME}
    secure: ${DOMAIN_SECURE}
    same-site: ${DOMAIN_SAME_SITE}

logging:
  level:
    com.erp: DEBUG
    org:
      springframework:
        security: DEBUG
        orm:
          jpa: DEBUG
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE
      hibernate.orm.jdbc.bind: TRACE

  jackson:
    date-format: dd-MM-yyyy hh:mm:ss a
    time-zone: Asia/Kolkata
    serialization:
      write-dates-as-timestamps: false

otp:
  service:
  url: https://cpaas.messagecentral.com
  customer-id: C-1C35A10D607A45B
  key: WWFnbmVzaDIzQA==
  scope: NEW
  country: IN
  email: example@example.com
  flowType: SMS

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}

server:
  connection-timeout: 60s
  tomcat:
    max-threads: 200
    accept-count: 100

redis:
  host: ${REDIS_DOMAIN}
  port: ${REDIS_PORT_NUMBER}
  timeout: ${REDIS_TIMEOUT}
