
-- For changing stocktrasfer constraints
-- . Drop old foreign key constraints
--ALTER TABLE stock_transfer
--    DROP CONSTRAINT IF EXISTS stocktransfer_from_branch_id_fkey,
--    DROP CONSTRAINT IF EXISTS stocktransfer_to_branch_id_fkey

-- . Add correct foreign key constraints
--ALTER TABLE stock_transfer
--    ADD CONSTRAINT fk_stock_transfer_from_branch
--        FOREIGN KEY (from_branch_branch_id) REFERENCES branch(branch_id),
--    ADD CONSTRAINT fk_stock_transfer_to_branch
--        FOREIGN KEY (to_branch_branch_id) REFERENCES branch(branch_id)



-- For changing company_details table.
-- 1. Drop existing table
DROP TABLE IF EXISTS company_details CASCADE;

-- 2. Recreate table
CREATE TABLE company_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    office_no INT,
    address_line1 VARCHAR(500),
    address_line2 VARCHAR(500),
    description TEXT,
    gst_number VARCHAR(50),
    pan_number VARCHAR(50),
    industry_type VARCHAR(100),
    review_status VARCHAR(50) DEFAULT 'PENDING',
    review_comment TEXT,
    contact_person_name VARCHAR(255),
    contact_person_email VARCHAR(255),
    contact_person_phone VARCHAR(20),
    pincode VARCHAR(10),
    city VARCHAR(100),
    state VARCHAR(100),
    reviewed_by VARCHAR(255),
    document_details JSONB,
    created_by BIGINT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by BIGINT,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);