-- src/main/resources/db/migration/tenant/V1__create_core_tenant_tables.sql
CREATE TABLE IF NOT EXISTS user_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    contact_no BIGINT,
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    schema_name VARCHAR(255) NOT NULL,
    created_by BIGINT,
    last_updated_by BIGINT
);


