CREATE TABLE IF NOT EXISTS service_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255),
    service_url TEXT,
    service_id BIGINT,

    CONSTRAINT fk_service
        FOREIGN KEY (service_id)
        REFERENCES service(service_id)
        ON DELETE CASCADE
);