--CREATE TABLE IF NOT EXISTS users (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    first_name VARCHAR(255),
--    last_name VARCHAR(255),
--    email VARCHAR(255) NOT NULL UNIQUE,
--    phone_no BIGINT,
--    designation VARCHAR(255),
--    password VARCHAR(255) NOT NULL,
--    is_active BOOLEAN DEFAULT TRUE,
--    schema_name VARCHAR(255) NOT NULL,
--    created_by_admin_id BIGINT,
--    created_at DATE NOT NULL,
--    last_modified_at DATE
--);

ALTER TABLE IF EXISTS users
ADD COLUMN module_name VARCHAR(60),
ADD COLUMN branch_name VARCHAR(60),
ADD COLUMN reporting_to VARCHAR(60);
