
-- Drop old varients table if exists (only after data migration)
--DROP TABLE IF EXISTS varients;
--DROP TABLE IF EXISTS inventory;

-- Recreate merged inventory table with a single branch_id reference
CREATE TABLE IF NOT EXISTS inventoryV2 (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Basic inventory info
    item_name VARCHAR(255),
    item_description VARCHAR(255),
    low_stock_threshold DOUBLE PRECISION,

    -- Timestamp fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Branch reference (single FK)
    branch_id BIGINT,
    FOREIGN KEY (branch_id) REFERENCES branch(branch_id),

    -- Product metadata
    brand_name VARCHAR(255),
    product_categories VARCHAR(255),
    hsn_code VARCHAR(255),
    sku_code VARCHAR(255),
    ean VARCHAR(255),
    is_returnable BOOLEAN,
    product_status VARCHAR(255),
    active BOOLEAN,

    -- Tax reference (Single FK)
    tax_id BIGINT,
    FOREIGN KEY (tax_id) REFERENCES tax(id),

    -- Variant fields merged into inventory
    stock_quantity DOUBLE PRECISION,
    selling_price_type VARCHAR(100),
    selling_price DOUBLE PRECISION,
    purchase_price_type VARCHAR(100),
    purchase_price DOUBLE PRECISION,
    unit_type VARCHAR(50),
    unit_type_value DOUBLE PRECISION,
    measurement_type VARCHAR(50),
    measurement DOUBLE PRECISION,
    expiry_date TIMESTAMP,

    -- Rental Fields
    is_rentable BOOLEAN DEFAULT FALSE,
    default_rental_rate DOUBLE PRECISION,
    rental_rate_frequency VARCHAR(20),   -- Daily / Weekly / Monthly
    default_deposit_amount BIGINT,
    insurance_value BIGINT,
    rental_product_quantity BIGINT,
    rental_product_status VARCHAR(30)
);

DROP TABLE IF EXISTS service_inventory;

CREATE TABLE IF NOT EXISTS service_inventory (
    service_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,

    PRIMARY KEY (service_id, item_id),

    CONSTRAINT fk_service
        FOREIGN KEY (service_id) REFERENCES service(service_id),

    CONSTRAINT fk_inventory
        FOREIGN KEY (item_id) REFERENCES inventoryV2(item_id)
);
