
-- Leads Changes
ALTER TABLE IF EXISTS leads
    ADD COLUMN lost_reason VARCHAR(255),
    ADD COLUMN converted_customer_id BIGINT,
    ADD COLUMN latest_quotation_id BIGINT,
    ADD COLUMN total_quotation BIGINT,
    ADD COLUMN service_category VARCHAR(255),
    ADD COLUMN sqrt NUMERIC(10,2),

    ADD CONSTRAINT FK_lead_customer
        FOREIGN KEY (converted_customer_id) REFERENCES customer(id),

    ADD CONSTRAINT FK_lead_quotation
        FOREIGN KEY (latest_quotation_id) REFERENCES quotations(id);

CREATE TABLE IF NOT EXISTS lead_service_mapper (
    lead_service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL
);


ALTER TABLE IF EXISTS customer
    ADD COLUMN alternate_phone VARCHAR(20),
    ADD COLUMN location_url VARCHAR(255),
    ADD COLUMN customer_type VARCHAR(20),
    ADD COLUMN service_category VARCHAR(20),
    ADD COLUMN sqrt NUMERIC(10,2),
    ADD COLUMN total_quotation BIGINT DEFAULT 0,
    ADD COLUMN total_sales_order BIGINT DEFAULT 0,
    ADD COLUMN total_invoices BIGINT DEFAULT 0;

CREATE TABLE IF NOT EXISTS customer_service_mapper(
    customer_service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL
);

