-- src/main/resources/db/migration/tenant/V2__create_additional_tenant_tables.sql
CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_no BIGINT,
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    schema_name VARCHAR(255) NOT NULL,
    created_by_admin_id BIGINT,
    created_at DATE NOT NULL,
    last_modified_at DATE
);

CREATE TABLE IF NOT EXISTS users_roles (
    users_id BIGINT NOT NULL,
    roles_role_id BIGINT NOT NULL,
    PRIMARY KEY (users_id, roles_role_id),
    FOREIGN KEY (users_id) REFERENCES users(id),
    FOREIGN KEY (roles_role_id) REFERENCES roles(role_id)
);

CREATE TABLE IF NOT EXISTS branch (
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(255),
    location VARCHAR(255),
    contact_info VARCHAR(255),
    created_at TIMESTAMP,
    branch_status VARCHAR(255) CHECK (branch_status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS ledger (
    ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    address VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bank_account (
    bank_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(255),
    bank_name VARCHAR(255) CHECK (bank_name IN ('HDFC', 'SBI', 'ICICI', 'AXIS', 'KOTAK')),
    opening_balance DOUBLE PRECISION NOT NULL,
    current_balance DOUBLE PRECISION NOT NULL,
    account_status VARCHAR(255) CHECK (account_status IN ('ACTIVE', 'INACTIVE')),
    created_by VARCHAR(255),
    created_at TIMESTAMP,
    last_modified_at TIMESTAMP,
    ledger_ledger_id BIGINT,
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id)
);