
-- Leads and Customer Branch Wise Connection
ALTER TABLE IF EXISTS leads
    ADD COLUMN branch_id BIGINT,
    ADD CONSTRAINT fk_branch_leads FOREIGN KEY (branch_id) REFERENCES branch(branch_id);

ALTER TABLE IF EXISTS customer
    ADD COLUMN branch_id BIGINT,
    ADD CONSTRAINT fk_branch_customer FOREIGN KEY (branch_id) REFERENCES branch(branch_id);



-- Follow Up Details
DROP TABLE IF EXISTS follow_up_details;
CREATE TABLE follow_up_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT,
    quotation_id BIGINT,
    follow_up_type VARCHAR(20) NOT NULL
        CHECK (follow_up_type IN ('CALL','MESSAGE','MEETING','EMAIL')),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING','DONE','CONVERTED','LOST')),

    notes TEXT,
    next_followup_date DATE,
    next_followup_time TIME,
    lost_reason TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    branch_id BIGINT,
    CONSTRAINT fk_followup_branch FOREIGN KEY (branch_id) REFERENCES branch(branch_id)
);
