
-- Task Image Table
CREATE TABLE IF NOT EXISTS task_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_url TEXT NOT NULL,
    document_name VARCHAR(255),
    task_id BIGINT NOT NULL,
    CONSTRAINT fk_task_documents_task
        FOREIGN KEY (task_id)
        REFERENCES task(task_id)
        ON DELETE CASCADE
);


ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS document_url TEXT;