
ALTER TABLE IF EXISTS task_documents
    ADD COLUMN IF NOT EXISTS document_type TEXT;

-- Inventory V2 Document Table
CREATE TABLE IF NOT EXISTS inventoryv2_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_url TEXT NOT NULL,
    document_name VARCHAR(255),
    inventoryv2_id BIGINT NOT NULL,
    CONSTRAINT fk_inventoryv2_documents_inventory
        FOREIGN KEY (inventoryv2_id)
        REFERENCES inventoryv2(item_id)
        ON DELETE CASCADE
);