-- src/main/resources/db/migration/tenant/V3__create_inventory_and_voucher_tables.sql
CREATE TABLE IF NOT EXISTS inventory (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255),
    item_quantity DOUBLE PRECISION NOT NULL,
    item_description VARCHAR(255),
    item_cost DOUBLE PRECISION NOT NULL,
    categories VARCHAR(255),
    low_stock_threshold DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    branch_branch_id BIGINT,
    FOREIGN KEY (branch_branch_id) REFERENCES branch(branch_id)
);


CREATE TABLE IF NOT EXISTS voucher (
    voucher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_type VARCHAR(255) CHECK (voucher_type IN ('SALES', 'PURCHASE', 'RECEIPTS', 'PAYMENTS')),
    voucher_index VARCHAR(255),
    start_date DATE,
    end_date DATE
);

CREATE TABLE IF NOT EXISTS master (
    master_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    voucher_type VARCHAR(255) CHECK (voucher_type IN ('SALES', 'PURCHASE', 'RECEIPTS', 'PAYMENTS')),
    amount DOUBLE PRECISION NOT NULL,
    tax_amount DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    reference_type VARCHAR(255) CHECK (reference_type IN ('NEWREF', 'AGAINREF', 'ADVANCEREF', 'ONACCOUNTREF')),
    transaction_status VARCHAR(255) CHECK (transaction_status IN ('UNPAID', 'PAID', 'PARTIALLY_PAID')),
    description VARCHAR(255),
    voucher_index VARCHAR(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    bankaccount_bank_account_id BIGINT,
    ledger_ledger_id BIGINT,
    voucher_voucher_id BIGINT,
    referencemaster_master_id BIGINT,
    FOREIGN KEY (bankaccount_bank_account_id) REFERENCES bank_account(bank_account_id),
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id),
    FOREIGN KEY (voucher_voucher_id) REFERENCES voucher(voucher_id),
    FOREIGN KEY (referencemaster_master_id) REFERENCES master(master_id)
);



CREATE TABLE IF NOT EXISTS tax (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_name VARCHAR(50) NOT NULL,
    tax_type VARCHAR(50) NOT NULL,
    tax_rate DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory_tax (
    inventories_item_id BIGINT NOT NULL,
    taxes_id BIGINT NOT NULL,
    PRIMARY KEY (inventories_item_id, taxes_id),
    FOREIGN KEY (inventories_item_id) REFERENCES inventory(item_id),
    FOREIGN KEY (taxes_id) REFERENCES tax(id)
);

CREATE TABLE IF NOT EXISTS invoice_generator (
    invoice_generated_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    master_master_id BIGINT,
    admin_id BIGINT,
    FOREIGN KEY (master_master_id) REFERENCES master(master_id),
    FOREIGN KEY (admin_id) REFERENCES user_admin(id)
);

CREATE TABLE IF NOT EXISTS line_items (
    line_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255),
    unit_price DOUBLE PRECISION NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    base_amount DOUBLE PRECISION NOT NULL,
    total_price DOUBLE PRECISION NOT NULL,
    voucher_type VARCHAR(255) CHECK (voucher_type IN ('SALES', 'PURCHASE', 'RECEIPTS', 'PAYMENTS')),
    date DATE DEFAULT CURRENT_DATE,
    inventory_item_id BIGINT,
    master_master_id BIGINT,
    FOREIGN KEY (inventory_item_id) REFERENCES inventory(item_id),
    FOREIGN KEY (master_master_id) REFERENCES master(master_id)
);

CREATE TABLE IF NOT EXISTS line_item_tax (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_rate DECIMAL(10, 2),
    tax_amount DOUBLE PRECISION NOT NULL,
    line_items_line_item_id BIGINT, -- matches Hibernate default naming
    tax_id BIGINT,
    FOREIGN KEY (line_items_line_item_id) REFERENCES line_items(line_item_id),
    FOREIGN KEY (tax_id) REFERENCES tax(id)
);

CREATE TABLE IF NOT EXISTS line_item_tax (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_rate DECIMAL(10, 2),
    tax_amount DOUBLE PRECISION NOT NULL,
    line_items_line_item_id BIGINT,
    tax_id BIGINT,
    FOREIGN KEY (line_items_line_item_id) REFERENCES line_items(line_item_id),
    FOREIGN KEY (tax_id) REFERENCES tax(id)
);


CREATE TABLE IF NOT EXISTS inventory_movement (
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_voucher_id BIGINT,
    line_items_line_item_id BIGINT,
    branch_branch_id BIGINT,
    inventory_item_id BIGINT,
    ledger_ledger_id BIGINT,
    item_quantity DOUBLE PRECISION NOT NULL,
    tran_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (voucher_voucher_id) REFERENCES voucher(voucher_id),
    FOREIGN KEY (line_items_line_item_id) REFERENCES line_items(line_item_id),
    FOREIGN KEY (branch_branch_id) REFERENCES branch(branch_id),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory(item_id),
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id)
);

CREATE TABLE IF NOT EXISTS against_ref_map (
    against_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type VARCHAR(50) CHECK (reference_type IN ('NEWREF', 'AGAINREF', 'ADVANCEREF', 'ONACCOUNTREF')),
    amount DOUBLE PRECISION NOT NULL,
    ledger_ledger_id BIGINT,
    master_master_id BIGINT,
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id),
    FOREIGN KEY (master_master_id) REFERENCES master(master_id)
);

ALTER TABLE inventory
ADD COLUMN IF NOT EXISTS brand_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS product_categories VARCHAR(255),
ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(255),
ADD COLUMN IF NOT EXISTS sku_code VARCHAR(255),
ADD COLUMN IF NOT EXISTS ean VARCHAR(255),
ADD COLUMN IF NOT EXISTS is_returnable BOOLEAN,
ADD COLUMN IF NOT EXISTS tax_id BIGINT,
ADD COLUMN IF NOT EXISTS product_status VARCHAR(255),
ADD COLUMN IF NOT EXISTS branch_id BIGINT;




