-- src/main/resources/db/migration/tenant/V3__create_inventory_and_voucher_tables.sql
CREATE TABLE IF NOT EXISTS inventory (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255),
    item_quantity DOUBLE PRECISION NOT NULL,
    item_description VARCHAR(255),
    item_cost DOUBLE PRECISION NOT NULL,
    categories VARCHAR(255),
    created_at TIMESTAMP,
    last_modified_at TIMESTAMP,
    branch_branch_id BIGINT,
    FOREIGN KEY (branch_branch_id) REFERENCES branch(branch_id)
);

CREATE TABLE IF NOT EXISTS voucher (
    voucher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_type VARCHAR(255) CHECK (voucher_type IN ('SALES', 'PURCHASE', 'RECEIPTS', 'PAYMENTS')),
    voucher_index VARCHAR(255),
    start_date DATE,
    end_date DATE
);

CREATE TABLE IF NOT EXISTS master (
    master_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    voucher_type VARCHAR(255) CHECK (voucher_type IN ('SALES', 'PURCHASE', 'RECEIPTS', 'PAYMENTS')),
    amount DOUBLE PRECISION NOT NULL,
    reference_type VARCHAR(255) CHECK (reference_type IN ('NEWREF', 'AGAINREF', 'ADVANCEREF', 'ONACCOUNTREF')),
    transaction_status VARCHAR(255) CHECK (transaction_status IN ('UNPAID', 'PAID', 'PARTIALLY_PAID')),
    description VARCHAR(255),
    voucher_index VARCHAR(255),
    created_date TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP,
    bank_account_bank_account_id BIGINT,
    ledger_ledger_id BIGINT,
    voucher_voucher_id BIGINT,
    FOREIGN KEY (bank_account_bank_account_id) REFERENCES bank_account(bank_account_id),
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id),
    FOREIGN KEY (voucher_voucher_id) REFERENCES voucher(voucher_id)
);