

CREATE TABLE IF NOT EXISTS technician_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technician_id BIGINT NOT NULL,
    fcm_token VARCHAR(512) NOT NULL,
    platform VARCHAR(10) NOT NULL
        CHECK (platform IN ('ANDROID', 'IOS')),
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_technician_fcm_tokens_technician
        FOREIGN KEY (technician_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_technician_fcm_token
        UNIQUE (technician_id, fcm_token)
);
