CREATE TABLE IF NOT EXISTS amc_contract (

    amc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    amc_number VARCHAR(100),
    amc_type VARCHAR(50),
    amc_category VARCHAR(50),

    recurring_type VARCHAR(50),
    recurring_interval INTEGER ,
    recurring_cycle INTEGER ,

    total_cycle INTEGER ,
    complete_cycle INTEGER ,
    remain_cycle INTEGER ,

    contract_start_date DATE,
    contract_end_date DATE,

    next_invoice_date DATE,
    last_invoice_date DATE,

    contract_total_value NUMERIC(15,2),
    per_cycle_amount NUMERIC(15,2),
    total_complete_amount NUMERIC(15,2),
    total_remain_amount NUMERIC(15,2),

    discount_amount NUMERIC(15,2),

    amc_status VARCHAR(30),
    pause_reason VARCHAR(255),
    termination_reason VARCHAR(255),

    auto_generate_invoice BOOLEAN,

    created_by BIGINT,
    updated_by BIGINT,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    -- FK columns (as per your entity)
    customer_id BIGINT NOT NULL,
    sales_order_id BIGINT NOT NULL,
    branch_id BIGINT,

    -- Foreign key constraints
    CONSTRAINT fk_amc_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer (id),

    CONSTRAINT fk_amc_sales_order
            FOREIGN KEY (sales_order_id)
            REFERENCES sales_orders (sales_order_number),

    CONSTRAINT fk_amc_branch
        FOREIGN KEY (branch_id)
        REFERENCES branch (branch_id)
);

ALTER TABLE IF EXISTS sales_orders
ADD COLUMN IF NOT EXISTS is_amc BOOLEAN NOT NULL DEFAULT FALSE;