-- src/main/resources/db/migration/tenant/V4__create_remaining_tenant_tables.sql

CREATE TABLE IF NOT EXISTS invoice_generator (
    invoice_generated_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount DOUBLE PRECISION NOT NULL,
    generated_at TIMESTAMP,
    ledger_ledger_id BIGINT,
    master_master_id BIGINT,
    FOREIGN KEY (master_master_id) REFERENCES master(master_id),
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id)
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    date DATE NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    working_hours DOUBLE PRECISION,
    working_days DOUBLE PRECISION,
    check_in TIMESTAMP,
    check_out TIMESTAMP,
    status VARCHAR(50) CHECK (status IN ('PRESENT', 'ABSENT', 'LEAVE', 'HOLIDAY')),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS holiday (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    date DATE DEFAULT CURRENT_DATE,
    description VARCHAR(255),
    department VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS leave_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    leave_type VARCHAR(255) CHECK (leave_type IN ('PAID', 'UNPAID')),
    reason TEXT,
    status VARCHAR(255) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    leave_balance INT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS salaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    month VARCHAR(7) NOT NULL, -- Storing YearMonth as 'YYYY-MM'
    base_salary BIGINT NOT NULL,
    working_days INT,
    paid_days INT,
    deductions BIGINT,
    bonus BIGINT,
    net_salary BIGINT,
    remarks VARCHAR(255),
    amount_status VARCHAR(255) NOT NULL CHECK (amount_status IN ('PENDING', 'PAID', 'FAILED')),
    payment_date VARCHAR(7), -- YearMonth stored as 'YYYY-MM'
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS service (
    service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    service_description VARCHAR(500),
    service_price DOUBLE PRECISION NOT NULL,
    service_status VARCHAR(50) CHECK (service_status IN ('AVAILABLE', 'UNAVAILABLE')),
    categories VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    contact_no VARCHAR(50),
    designation VARCHAR(50) CHECK (designation IN ('MANAGER', 'SALESPERSON', 'ACCOUNTANT', 'HR', 'TECHNICIAN')),
    staff_status VARCHAR(50) CHECK (staff_status IN ('ACTIVE', 'INACTIVE', 'TERMINATED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    branch_branch_id BIGINT,
    FOREIGN KEY (branch_branch_id) REFERENCES branch(branch_id)
);

CREATE TABLE IF NOT EXISTS stock_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_branch_branch_id BIGINT,
    to_branch_branch_id BIGINT,
    inventory_item_id BIGINT,
    quantity DOUBLE PRECISION NOT NULL,
    status VARCHAR(50) CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    approved_by VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (from_branch_branch_id) REFERENCES branch(branch_id),
    FOREIGN KEY (to_branch_branch_id) REFERENCES branch(branch_id),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory(item_id)
);

CREATE TABLE task_material (
    task_material_id BIGSERIAL PRIMARY KEY,
    task_id          BIGINT NOT NULL,
    material_id      BIGINT NOT NULL,
    unit             DOUBLE PRECISION,
    is_used          BOOLEAN
);

CREATE TABLE task (
    task_id BIGSERIAL PRIMARY KEY,
    task_name VARCHAR(255) NOT NULL,
    customer_id BIGINT NOT NULL,
    task_category VARCHAR(255),
    task_details TEXT,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE TABLE task_services (
    task_service_id BIGSERIAL PRIMARY KEY,
    task_id         BIGINT NOT NULL,
    service_id      BIGINT NOT NULL
);

CREATE TABLE task_schedule (
    task_schedule_id     BIGSERIAL PRIMARY KEY,
    task_id              BIGINT NOT NULL,
    assigned_date        DATE,
    assigned_time        TIME,
    google_location_link VARCHAR(255),
    field_type           VARCHAR(255),
    service_location     VARCHAR(255),
    feedback_id          BIGINT,
    task_start_time      TIME,
    task_end_time        TIME
);


CREATE TABLE leaderboard (
    id BIGSERIAL PRIMARY KEY,
    technician_id BIGINT NOT NULL,
    rank INT NOT NULL
);

