-- src/main/resources/db/migration/tenant/V4__create_remaining_tenant_tables.sql
CREATE TABLE IF NOT EXISTS line_items (
    line_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255),
    unit_price DOUBLE PRECISION NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    total_price DOUBLE PRECISION NOT NULL,
    voucher_type VARCHAR(255) CHECK (voucher_type IN ('SALES', 'PURCHASE', 'RECEIPTS', 'PAYMENTS')),
    date DATE,
    inventory_item_id BIGINT,
    master_master_id BIGINT,
    FOREIGN KEY (inventory_item_id) REFERENCES inventory(item_id),
    FOREIGN KEY (master_master_id) REFERENCES master(master_id)
);

CREATE TABLE IF NOT EXISTS against_ref_map (
    against_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type VARCHAR(255) CHECK (reference_type IN ('NEWREF', 'AGAINREF', 'ADVANCEREF', 'ONACCOUNTREF')),
    amount DOUBLE PRECISION NOT NULL,
    ledger_ledger_id BIGINT,
    master_master_id BIGINT,
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id),
    FOREIGN KEY (master_master_id) REFERENCES master(master_id)
);

CREATE TABLE IF NOT EXISTS invoice_generator (
    invoice_generated_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount DOUBLE PRECISION NOT NULL,
    generated_at TIMESTAMP,
    ledger_ledger_id BIGINT,
    master_master_id BIGINT,
    FOREIGN KEY (master_master_id) REFERENCES master(master_id),
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id)
);

CREATE TABLE IF NOT EXISTS inventory_movement (
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_quantity DOUBLE PRECISION NOT NULL,
    tran_date TIMESTAMP,
    voucher_voucher_id BIGINT,
    line_item_line_item_id BIGINT,
    branch_branch_id BIGINT,
    inventory_item_id BIGINT,
    ledger_ledger_id BIGINT,
    FOREIGN KEY (voucher_voucher_id) REFERENCES voucher(voucher_id),
    FOREIGN KEY (line_item_line_item_id) REFERENCES line_items(line_item_id),
    FOREIGN KEY (branch_branch_id) REFERENCES branch(branch_id),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory(item_id),
    FOREIGN KEY (ledger_ledger_id) REFERENCES ledger(ledger_id)
);

CREATE TABLE IF NOT EXISTS holiday (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    date DATE,
    description VARCHAR(255),
    department VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS leave_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    leave_type VARCHAR(255) CHECK (leave_type IN ('PAID', 'UNPAID')),
    reason TEXT,
    status VARCHAR(255) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS salaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    month DATE NOT NULL,
    base_salary BIGINT NOT NULL,
    working_days INTEGER NOT NULL,
    paid_days INTEGER NOT NULL,
    deductions BIGINT NOT NULL,
    bonus BIGINT NOT NULL,
    net_salary BIGINT NOT NULL,
    remarks VARCHAR(255),
    amount_status VARCHAR(255) NOT NULL CHECK (amount_status IN ('PENDING', 'PAID', 'FAILED')),
    payment_date DATE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);