CREATE SEQUENCE IF NOT EXISTS company_details_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS company_details (
    id BIGINT PRIMARY KEY DEFAULT nextval('company_details_seq'),
    name VARCHAR(255),
    address VARCHAR(1000),
    industry_type VARCHAR(50),
    description TEXT,
    gst_number VARCHAR(50),
    pan_number VARCHAR(50),
    review_status VARCHAR(50) DEFAULT 'PENDING',
    review_comment TEXT,
    reviewed_by VARCHAR(255),
    createdby_id BIGINT,
    createddate TIMESTAMP,
    lastmodifiedby_id BIGINT,
    lastmodifieddate TIMESTAMP
);

CREATE TABLE IF NOT EXISTS document_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_name VARCHAR(255),
    document_url VARCHAR(255),
    company_details_id BIGINT,
    -- other fields as per DocumentDetails entity
    CONSTRAINT fk_company_details
        FOREIGN KEY (company_details_id)
        REFERENCES company_details(id)
        ON DELETE CASCADE
);