--CREATE SEQUENCE IF NOT EXISTS company_details_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE company_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    office_no INT,
    address_line1 VARCHAR(500),
    address_line2 VARCHAR(500),
    description TEXT,
    gst_number VARCHAR(50),
    pan_number VARCHAR(50),
    industry_type VARCHAR(100),
    review_status VARCHAR(50) DEFAULT 'PENDING',
    review_comment TEXT,
    contact_person_name VARCHAR(255),
    contact_person_email VARCHAR(255),
    contact_person_phone VARCHAR(20),
    pincode VARCHAR(10),
    city VARCHAR(100),
    state VARCHAR(100),
    reviewed_by VARCHAR(255),
    document_details JSONB,
    created_by BIGINT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by BIGINT,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS document_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_name VARCHAR(255),
    document_url VARCHAR(255),
    company_details_id BIGINT,
    -- other fields as per DocumentDetails entity
    CONSTRAINT fk_company_details
        FOREIGN KEY (company_details_id)
        REFERENCES company_details(id)
        ON DELETE CASCADE
);