-- Create Account Group table
CREATE TABLE IF NOT EXISTS account_group (
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(255) NOT NULL UNIQUE,
    group_code VARCHAR(10) NOT NULL UNIQUE,
    group_type VARCHAR(50) NOT NULL CHECK (group_type IN ('ASSETS', 'LIABILITIES', 'EQUITY', 'INCOME', 'EXPENSES')),
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Account SubGroup table
CREATE TABLE IF NOT EXISTS account_subgroup (
    subgroup_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subgroup_name VARCHAR(255) NOT NULL,
    subgroup_code VARCHAR(15) NOT NULL UNIQUE,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER,
    group_id BIGINT NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES account_group(group_id)
);

-- Add new columns to existing ledger table
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS ledger_code VARCHAR(20) UNIQUE;
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS pan_no VARCHAR(20);
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS opening_balance DECIMAL(19,2) DEFAULT 0.00;
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS balance_type VARCHAR(10) DEFAULT 'DEBIT' CHECK (balance_type IN ('DEBIT', 'CREDIT'));
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS current_balance DECIMAL(19,2) DEFAULT 0.00;
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS group_id BIGINT;
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS subgroup_id BIGINT;

-- Add foreign key constraints for ledger table
ALTER TABLE ledger ADD CONSTRAINT fk_ledger_account_group 
    FOREIGN KEY (group_id) REFERENCES account_group(group_id);
ALTER TABLE ledger ADD CONSTRAINT fk_ledger_account_subgroup 
    FOREIGN KEY (subgroup_id) REFERENCES account_subgroup(subgroup_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_account_group_type ON account_group(group_type);
CREATE INDEX IF NOT EXISTS idx_account_group_active ON account_group(is_active);
CREATE INDEX IF NOT EXISTS idx_account_subgroup_group ON account_subgroup(group_id);
CREATE INDEX IF NOT EXISTS idx_account_subgroup_active ON account_subgroup(is_active);
CREATE INDEX IF NOT EXISTS idx_ledger_group ON ledger(group_id);
CREATE INDEX IF NOT EXISTS idx_ledger_subgroup ON ledger(subgroup_id);
CREATE INDEX IF NOT EXISTS idx_ledger_active ON ledger(is_active);
CREATE INDEX IF NOT EXISTS idx_ledger_code ON ledger(ledger_code);

-- Insert standard account groups
INSERT INTO account_group (group_name, group_code, group_type, description, sort_order) VALUES
('Fixed Assets', 'FA', 'ASSETS', 'Tangible and intangible assets used in business operations', 1),
('Current Assets', 'CA', 'ASSETS', 'Assets expected to be converted to cash within one year', 2),
('Investments', 'INV', 'ASSETS', 'Long-term investments and securities', 3),
('Current Liabilities', 'CL', 'LIABILITIES', 'Debts due within one year', 4),
('Long Term Liabilities', 'LTL', 'LIABILITIES', 'Debts due after one year', 5),
('Capital', 'CAP', 'EQUITY', 'Owner''s equity and capital contributions', 6),
('Reserves & Surplus', 'RES', 'EQUITY', 'Retained earnings and reserves', 7),
('Direct Income', 'DI', 'INCOME', 'Revenue from primary business operations', 8),
('Indirect Income', 'II', 'INCOME', 'Revenue from secondary sources', 9),
('Direct Expenses', 'DE', 'EXPENSES', 'Costs directly related to revenue generation', 10),
('Indirect Expenses', 'IE', 'EXPENSES', 'Operating expenses not directly related to revenue', 11)
ON CONFLICT (group_code) DO NOTHING;

-- Insert standard account subgroups
INSERT INTO account_subgroup (subgroup_name, subgroup_code, description, group_id, sort_order) 
SELECT 
    sg.subgroup_name,
    sg.subgroup_code,
    sg.description,
    ag.group_id,
    sg.sort_order
FROM (
    VALUES 
        ('Land & Building', 'LAND', 'Land and building assets', 'Fixed Assets', 1),
        ('Plant & Machinery', 'PM', 'Plant and machinery assets', 'Fixed Assets', 2),
        ('Furniture & Fixtures', 'FF', 'Furniture and fixtures', 'Fixed Assets', 3),
        ('Computer & Software', 'CS', 'Computer equipment and software', 'Fixed Assets', 4),
        ('Cash & Bank', 'CB', 'Cash and bank accounts', 'Current Assets', 1),
        ('Accounts Receivable', 'AR', 'Outstanding customer payments', 'Current Assets', 2),
        ('Inventory', 'INV', 'Stock and inventory', 'Current Assets', 3),
        ('Accounts Payable', 'AP', 'Outstanding vendor payments', 'Current Liabilities', 1),
        ('Loans & Advances', 'LA', 'Short-term loans and advances', 'Current Liabilities', 2),
        ('Equity Capital', 'EC', 'Owner''s capital contribution', 'Capital', 1),
        ('Retained Earnings', 'RE', 'Accumulated profits', 'Reserves & Surplus', 1),
        ('Sales', 'SALES', 'Revenue from sales', 'Direct Income', 1),
        ('Service Income', 'SI', 'Revenue from services', 'Direct Income', 2),
        ('Interest Income', 'II', 'Interest earned', 'Indirect Income', 1),
        ('Purchase', 'PURCHASE', 'Cost of goods purchased', 'Direct Expenses', 1),
        ('Direct Labor', 'DL', 'Direct labor costs', 'Direct Expenses', 2),
        ('Administrative Expenses', 'AE', 'General administrative costs', 'Indirect Expenses', 1),
        ('Marketing Expenses', 'ME', 'Marketing and promotional costs', 'Indirect Expenses', 2)
) AS sg(subgroup_name, subgroup_code, description, group_name, sort_order)
JOIN account_group ag ON ag.group_name = sg.group_name
ON CONFLICT (subgroup_code) DO NOTHING;
