CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technician_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    customer_location VARCHAR(255) NOT NULL,
    task_id BIGINT NOT NULL,
    issue_description VARCHAR(1000),
    priority VARCHAR(50) NOT NULL,
    ticket_status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP
);
