-- =========================================================
-- ACCOUNTS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    industry VARCHAR(255),
    website VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- CONTACTS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    account_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);

-- index on email (for faster search)
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);

-- =========================================================
-- LEADS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    source VARCHAR(255),
    status VARCHAR(50) CHECK (status IN ('NEW','CONTACTED','QUALIFIED','LOST','CONVERTED')),
    assigned_to_id BIGINT,
    assigned_to_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- index on email (for faster search)
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);

-- =========================================================
-- DEALS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    amount NUMERIC(15,2),
    stage VARCHAR(50) CHECK (stage IN ('PROSPECTING','QUALIFICATION','PROPOSAL','NEGOTIATION','CLOSED_WON','CLOSED_LOST')),
    close_date DATE,
    contact_id BIGINT,
    account_id BIGINT,
    assigned_to_id BIGINT,
    assigned_to_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contact_id) REFERENCES contacts(id),
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);

-- =========================================================
-- NOTIFICATIONS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    message TEXT NOT NULL,
    timestamp BIGINT,
    from_user VARCHAR(255),
    to_user VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    read_at BIGINT,
    type VARCHAR(100)
);