-- Enhanced Voucher System Migration
-- This migration adds new voucher types and transaction entry system

-- Update voucher table with new columns
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS voucher_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS voucher_status VARCHAR(50) NOT NULL DEFAULT 'DRAFT' CHECK (voucher_status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'REJECTED', 'CANCELLED'));
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS total_amount DECIMAL(19,2) DEFAULT 0.00;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS debit_total DECIMAL(19,2) DEFAULT 0.00;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS credit_total DECIMAL(19,2) DEFAULT 0.00;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS narration TEXT;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS reference_number VARCHAR(100);
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN DEFAULT FALSE;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS recurring_frequency VARCHAR(20);
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS recurring_end_date DATE;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS next_recurring_date DATE;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS is_reversed BOOLEAN DEFAULT FALSE;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS reversed_voucher_id BIGINT;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS modified_by VARCHAR(255);
ALTER TABLE voucher ADD COLUMN IF NOT EXISTS modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Update voucher_type constraint to include new types
ALTER TABLE voucher DROP CONSTRAINT IF EXISTS voucher_voucher_type_check;
ALTER TABLE voucher ADD CONSTRAINT voucher_voucher_type_check 
    CHECK (voucher_type IN ('SALES', 'PURCHASE', 'RECEIPTS', 'PAYMENTS', 'CONTRA', 'JOURNAL', 'CREDIT_NOTE', 'DEBIT_NOTE', 'RECURRING', 'OPENING_BALANCE', 'CLOSING_ENTRY', 'DEPRECIATION', 'PROVISION', 'ADJUSTMENT'));

-- Create Transaction Entry table
CREATE TABLE IF NOT EXISTS transaction_entry (
    entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    ledger_id BIGINT NOT NULL,
    entry_type VARCHAR(10) NOT NULL CHECK (entry_type IN ('DEBIT', 'CREDIT')),
    amount DECIMAL(19,2) NOT NULL,
    description TEXT,
    reference_number VARCHAR(100),
    cheque_number VARCHAR(50),
    cheque_date TIMESTAMP,
    is_reconciled BOOLEAN DEFAULT FALSE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (voucher_id) REFERENCES voucher(voucher_id) ON DELETE CASCADE,
    FOREIGN KEY (ledger_id) REFERENCES ledger(ledger_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_voucher_date ON voucher(voucher_date);
CREATE INDEX IF NOT EXISTS idx_voucher_status ON voucher(voucher_status);
CREATE INDEX IF NOT EXISTS idx_voucher_type ON voucher(voucher_type);
CREATE INDEX IF NOT EXISTS idx_voucher_recurring ON voucher(is_recurring);
CREATE INDEX IF NOT EXISTS idx_transaction_entry_voucher ON transaction_entry(voucher_id);
CREATE INDEX IF NOT EXISTS idx_transaction_entry_ledger ON transaction_entry(ledger_id);
CREATE INDEX IF NOT EXISTS idx_transaction_entry_type ON transaction_entry(entry_type);
CREATE INDEX IF NOT EXISTS idx_transaction_entry_reconciled ON transaction_entry(is_reconciled);

-- Update existing voucher records to have proper dates
UPDATE voucher SET voucher_date = COALESCE(start_date, CURRENT_DATE) WHERE voucher_date IS NULL;

-- Add foreign key constraint for reversed voucher reference
ALTER TABLE voucher ADD CONSTRAINT fk_voucher_reversed 
    FOREIGN KEY (reversed_voucher_id) REFERENCES voucher(voucher_id);

-- Create audit trail table for voucher changes
CREATE TABLE IF NOT EXISTS voucher_audit_trail (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL, -- CREATED, UPDATED, POSTED, REVERSED, etc.
    old_status VARCHAR(50),
    new_status VARCHAR(50),
    changed_by VARCHAR(255) NOT NULL,
    change_reason TEXT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (voucher_id) REFERENCES voucher(voucher_id)
);

CREATE INDEX IF NOT EXISTS idx_voucher_audit_voucher ON voucher_audit_trail(voucher_id);
CREATE INDEX IF NOT EXISTS idx_voucher_audit_action ON voucher_audit_trail(action);
CREATE INDEX IF NOT EXISTS idx_voucher_audit_date ON voucher_audit_trail(created_date);

-- Create recurring voucher schedule table
CREATE TABLE IF NOT EXISTS recurring_voucher_schedule (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    next_execution_date DATE NOT NULL,
    execution_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    last_executed_date DATE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (voucher_id) REFERENCES voucher(voucher_id)
);

CREATE INDEX IF NOT EXISTS idx_recurring_schedule_next_date ON recurring_voucher_schedule(next_execution_date);
CREATE INDEX IF NOT EXISTS idx_recurring_schedule_active ON recurring_voucher_schedule(is_active);

-- Insert sample ledger codes for standard accounts if they don't exist
INSERT INTO ledger (name, ledger_code, is_active, group_id, subgroup_id, opening_balance, balance_type)
SELECT 
    'Cash Account',
    'CASH001',
    true,
    ag.group_id,
    asg.subgroup_id,
    0.00,
    'DEBIT'
FROM account_group ag
JOIN account_subgroup asg ON ag.group_id = asg.group_id
WHERE ag.group_code = 'CA' AND asg.subgroup_code = 'CB'
AND NOT EXISTS (SELECT 1 FROM ledger WHERE ledger_code = 'CASH001')
LIMIT 1;

INSERT INTO ledger (name, ledger_code, is_active, group_id, subgroup_id, opening_balance, balance_type)
SELECT 
    'Bank Account - HDFC',
    'BANK001',
    true,
    ag.group_id,
    asg.subgroup_id,
    0.00,
    'DEBIT'
FROM account_group ag
JOIN account_subgroup asg ON ag.group_id = asg.group_id
WHERE ag.group_code = 'CA' AND asg.subgroup_code = 'CB'
AND NOT EXISTS (SELECT 1 FROM ledger WHERE ledger_code = 'BANK001')
LIMIT 1;
