-- =========================================================
-- TECHNICIAN TASK TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS technician_task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING','IN_PROGRESS','COMPLETED','FAILED')),
    assigned_at TIMESTAMP,
    completed_at TIMESTAMP,
    feedback TEXT,
    client_name VARCHAR(150),
    client_location VARCHAR(255),
    service_type VARCHAR(100),
    scheduled_at TIMESTAMP,
    scheduled_for TIMESTAMP,
    started_at TIMESTAMP,
    job_latitude DOUBLE PRECISION,
    job_longitude DOUBLE PRECISION,
    job_radius_meters INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =========================================================
-- TECHNICIAN LOCATION TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS technician_location (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    attendance_id BIGINT,
    task_id BIGINT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    altitude DOUBLE PRECISION,
    speed REAL,
    bearing REAL,
    accuracy REAL,
    provider VARCHAR(255),
    battery_level INTEGER,
    note TEXT,
    image_url VARCHAR(500),
    recorded_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (attendance_id) REFERENCES attendance(id),
    FOREIGN KEY (task_id) REFERENCES technician_task(task_id)
);

-- =========================================================
-- TECHNICIAN PERFORMANCE TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS technician_performance (
    performance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    year INTEGER NOT NULL,
    punctuality_score NUMERIC(5,2),
    task_completion_score NUMERIC(5,2),
    overtime_score NUMERIC(5,2),
    customer_feedback_score NUMERIC(5,2),
    final_rating NUMERIC(5,2),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =========================================================
-- TECHNICIAN SHIFTS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS technician_shifts (
    shift_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    shift_name VARCHAR(255),
    shift_start TIMESTAMP,
    shift_end TIMESTAMP,
    shift_type VARCHAR(50) CHECK (shift_type IN ('MORNING','NIGHT','CUSTOM')),
    is_active BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =========================================================
-- CUSTOMER SUPPORT TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS support_requests (
    support_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technician_id BIGINT,
    task_id BIGINT,
    customer_name VARCHAR(255),
    customer_contact VARCHAR(100),
    issue_description TEXT,
    priority VARCHAR(20) CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    status VARCHAR(20) CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    feedback TEXT,
    FOREIGN KEY (technician_id) REFERENCES users(id),
    FOREIGN KEY (task_id) REFERENCES technician_task(task_id)
);