-- Banking Module Migration
-- This migration creates tables for bank statement import and reconciliation

-- Create Bank Statement table
CREATE TABLE IF NOT EXISTS bank_statement (
    statement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_account_id BIGINT NOT NULL,
    statement_date DATE NOT NULL,
    opening_balance DECIMAL(19,2),
    closing_balance DECIMAL(19,2),
    total_debits DECIMAL(19,2) DEFAULT 0.00,
    total_credits DECIMAL(19,2) DEFAULT 0.00,
    statement_reference VARCHAR(100),
    statement_status VARCHAR(50) NOT NULL DEFAULT 'IMPORTED' CHECK (statement_status IN ('IMPORTED', 'PROCESSING', 'PROCESSED', 'RECONCILED', 'ERROR')),
    import_source VARCHAR(50), -- CSV, EXCEL, API, MANUAL
    import_file_name VARCHAR(255),
    notes TEXT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(bank_account_id)
);

-- Create Bank Statement Line table
CREATE TABLE IF NOT EXISTS bank_statement_line (
    line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    value_date DATE,
    description TEXT NOT NULL,
    reference_number VARCHAR(100),
    cheque_number VARCHAR(50),
    amount DECIMAL(19,2) NOT NULL,
    transaction_type VARCHAR(10) NOT NULL CHECK (transaction_type IN ('DEBIT', 'CREDIT')),
    reconciliation_status VARCHAR(50) NOT NULL DEFAULT 'UNRECONCILED' CHECK (reconciliation_status IN ('UNRECONCILED', 'MATCHED', 'MANUAL', 'DISPUTED', 'RECONCILED')),
    balance_after DECIMAL(19,2),
    notes TEXT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Reconciliation fields
    matched_transaction_entry_id BIGINT,
    reconciliation_date TIMESTAMP,
    reconciled_by VARCHAR(255),
    FOREIGN KEY (statement_id) REFERENCES bank_statement(statement_id) ON DELETE CASCADE,
    FOREIGN KEY (matched_transaction_entry_id) REFERENCES transaction_entry(entry_id)
);

-- Create Bank Reconciliation Summary table
CREATE TABLE IF NOT EXISTS bank_reconciliation_summary (
    reconciliation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_account_id BIGINT NOT NULL,
    statement_id BIGINT NOT NULL,
    reconciliation_date DATE NOT NULL,
    statement_balance DECIMAL(19,2) NOT NULL,
    book_balance DECIMAL(19,2) NOT NULL,
    reconciled_amount DECIMAL(19,2) NOT NULL,
    unreconciled_amount DECIMAL(19,2) NOT NULL,
    total_transactions INTEGER DEFAULT 0,
    reconciled_transactions INTEGER DEFAULT 0,
    unreconciled_transactions INTEGER DEFAULT 0,
    is_balanced BOOLEAN NOT NULL,
    notes TEXT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(bank_account_id),
    FOREIGN KEY (statement_id) REFERENCES bank_statement(statement_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_bank_statement_account ON bank_statement(bank_account_id);
CREATE INDEX IF NOT EXISTS idx_bank_statement_date ON bank_statement(statement_date);
CREATE INDEX IF NOT EXISTS idx_bank_statement_status ON bank_statement(statement_status);
CREATE INDEX IF NOT EXISTS idx_bank_statement_line_statement ON bank_statement_line(statement_id);
CREATE INDEX IF NOT EXISTS idx_bank_statement_line_date ON bank_statement_line(transaction_date);
CREATE INDEX IF NOT EXISTS idx_bank_statement_line_status ON bank_statement_line(reconciliation_status);
CREATE INDEX IF NOT EXISTS idx_bank_statement_line_matched ON bank_statement_line(matched_transaction_entry_id);
CREATE INDEX IF NOT EXISTS idx_reconciliation_summary_account ON bank_reconciliation_summary(bank_account_id);
CREATE INDEX IF NOT EXISTS idx_reconciliation_summary_date ON bank_reconciliation_summary(reconciliation_date);

-- Update existing bank_account table to add reconciliation fields
ALTER TABLE bank_account ADD COLUMN IF NOT EXISTS last_reconciliation_date DATE;
ALTER TABLE bank_account ADD COLUMN IF NOT EXISTS last_statement_date DATE;
ALTER TABLE bank_account ADD COLUMN IF NOT EXISTS reconciliation_frequency VARCHAR(20) DEFAULT 'MONTHLY';

-- Create view for bank reconciliation summary
CREATE OR REPLACE VIEW bank_reconciliation_view AS
SELECT 
    bs.statement_id,
    bs.bank_account_id,
    ba.bank_name AS account_name,
    ba.account_number,
    bs.statement_date,
    bs.opening_balance,
    bs.closing_balance,
    bs.total_debits,
    bs.total_credits,
    COUNT(bsl.line_id) as total_lines,
    COUNT(CASE WHEN bsl.reconciliation_status = 'RECONCILED' THEN 1 END) as reconciled_lines,
    COUNT(CASE WHEN bsl.reconciliation_status = 'UNRECONCILED' THEN 1 END) as unreconciled_lines,
    bs.statement_status,
    bs.created_date
FROM bank_statement bs
JOIN bank_account ba ON bs.bank_account_id = ba.bank_account_id
LEFT JOIN bank_statement_line bsl ON bs.statement_id = bsl.statement_id
GROUP BY bs.statement_id, bs.bank_account_id, ba.bank_name, ba.account_number, 
         bs.statement_date, bs.opening_balance, bs.closing_balance, 
         bs.total_debits, bs.total_credits, bs.statement_status, bs.created_date;

-- Create function to calculate bank balance as of date
CREATE OR REPLACE FUNCTION get_bank_balance_as_of(account_id BIGINT, as_of_date DATE)
RETURNS DECIMAL(19,2) AS $$
DECLARE
    balance DECIMAL(19,2) := 0.00;
BEGIN
    SELECT COALESCE(SUM(
        CASE 
            WHEN te.entry_type = 'DEBIT' THEN te.amount
            ELSE -te.amount
        END
    ), 0.00)
    INTO balance
    FROM transaction_entry te
    JOIN voucher v ON te.voucher_id = v.voucher_id
    WHERE te.ledger_id = account_id
    AND v.voucher_date <= as_of_date
    AND v.voucher_status = 'POSTED';
    
    RETURN balance;
END;
$$ LANGUAGE plpgsql;

-- Create function to auto-match transactions
CREATE OR REPLACE FUNCTION auto_match_transactions(statement_line_id BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
    stmt_line RECORD;
    matched_entry_id BIGINT;
BEGIN
    -- Get statement line details
    SELECT * INTO stmt_line 
    FROM bank_statement_line 
    WHERE line_id = statement_line_id;
    
    -- Find matching transaction entry
    SELECT te.entry_id INTO matched_entry_id
    FROM transaction_entry te
    JOIN voucher v ON te.voucher_id = v.voucher_id
    WHERE te.ledger_id = (
        SELECT ledger_id FROM ledger 
        WHERE name LIKE '%' || (
            SELECT bank_name FROM bank_account 
            WHERE bank_account_id = (
                SELECT bank_account_id FROM bank_statement 
                WHERE statement_id = stmt_line.statement_id
            )
        ) || '%'
    )
    AND ABS(te.amount - stmt_line.amount) < 0.01
    AND v.voucher_date = stmt_line.transaction_date
    AND te.is_reconciled = FALSE
    LIMIT 1;
    
    -- If match found, update statement line
    IF matched_entry_id IS NOT NULL THEN
        UPDATE bank_statement_line 
        SET 
            matched_transaction_entry_id = matched_entry_id,
            reconciliation_status = 'MATCHED',
            reconciliation_date = CURRENT_TIMESTAMP,
            reconciled_by = 'SYSTEM'
        WHERE line_id = statement_line_id;
        
        -- Mark transaction entry as reconciled
        UPDATE transaction_entry 
        SET is_reconciled = TRUE 
        WHERE entry_id = matched_entry_id;
        
        RETURN TRUE;
    END IF;
    
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql;
