-- Global public schema migrations
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.root_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.meta_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_email VARCHAR(255) NOT NULL UNIQUE,
    schema_name VARCHAR(255) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.token_black_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    expiration BIGINT NOT NULL
);

CREATE TABLE subscription (
    subscriptionid BIGSERIAL PRIMARY KEY,
    userid VARCHAR(255) NOT NULL,
    accountuser VARCHAR(255),
    subscriptionplan VARCHAR(100) NOT NULL,
    planperiod VARCHAR(50),
    planstartdate DATE,
    planenddate DATE,
    branchcode VARCHAR(50),
    companycode VARCHAR(50),
    paymentstatus VARCHAR(20),
    paymentid VARCHAR(255),
    activeYn CHAR(1)
);
